### ISSUE TITLE
Neutronium Ingot is recipe looped making Neutron Collector and Neutronium unobtainable

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [agileMuffin/MC-Celestial#1]
Hello. After looking at the recipes I found a loop for a bunch of creative recipes. It makes Neutron Collector and Neutronium unobtainable. Neutronium Collectors requires The Ultimate Ingot, but The Ultimate Ingot requires Neutronium, Neutronium can be obtained in Neutronium Collectors. Also on the server because of MCreator bug on Avaritia Lite's end - there are missing blocks from the mod such as Neutronium Collector/Compressor and others.

**Pictures:**
![image](https://user-images.githubusercontent.com/27882185/119226394-42dd1780-bb22-11eb-8378-555f161850e1.png)
![image](https://user-images.githubusercontent.com/27882185/119226403-512b3380-bb22-11eb-9362-2e708f0f9a19.png)

**Solution:**
To solve it - just use something difficult, that don't require Neutronium for Neutron Collector recipe or add another way to get Neutronium.
You can use my own KubeJS script to solve it on the dedicated server + remove that loop + make player's life a bit harder.
KubeJS Script with a lot of comments about time spent and what this script does. Works as intended in 1.0.5+ for me:
https://gist.github.com/DenisMasterHerobrine/242c594a8f546a7c821cafaf73ce0c7b (you can download easily and everyone can use it if someone want to play with it without any permission, feel free to use this script or it's part everywhere you want. Neutronium requires different mods to be automated before gathering some piles of it!)
Put this script into kubejs/server_scripts folder on client (and server too!).

Also I mentioned that there is no way to obtain Neutronium on the server because there is no any blocks registered from Avaritia Lite. So when the server is loaded - scripts being broken.
![image](https://user-images.githubusercontent.com/27882185/119227391-06f88100-bb27-11eb-911f-62f8afa2feac.png)

**Solution 2:**
Add a way of obtaining Neutronium through other mods and add through KubeJS a Neutronium Block with it's texture and change all recipes using Neutronium Block from Avaritia Lite to KubeJS ones to avoid missing recipes and broken recipes on the server or LAN world. 

If any other information is needed - feel free to ask me here.

**Comment by agileMuffin** [comment]
Hi! Thanks for letting me know about the issue. I have fixed the recipe for the same. In the future please don't hesitate to post more about the bugs.
