### ISSUE TITLE
Crash during mod loading

### ISSUE THREAD

**Issue by dlswimmer** [agileMuffin/MC-Celestial#2]
Latest Log - https://pastebin.com/XtcnSGre
Crash Log - https://pastebin.com/NLqciXVD

**Comment by agileMuffin** [comment]
I have no idea why this only happens to you, but it seems that ae wireless terminals mod is the cause. Try removing the mod and restarting your game.

**Comment by DenisMasterHerobrine** [comment]
This crash was already reported to the dev of AE2WT:
https://github.com/Tfarcenim/AE2WirelessTerminalLibrary/issues/7

Currently you can just remove AE2WTLib and run this modpack fine and re-add when this mod will be more stable to play with these terminals. The reason of the crash is missing WirelessCraftingStatusContainer in AE2, while AE2WT tries to implement it, not expert modder here, but maybe something wrong with dependencies of the mod.
