### ISSUE TITLE
Trees break dirt and other blocks

### ISSUE THREAD

**Issue by Applemyp** [agileMuffin/MC-Celestial#5]
So when you first load up and start growing trees, some times the tree is some sort of modded variant that grows roots and breaks the blocks under the sapling, its not just for oak, it also does that for spruce (all I tested). It probably does that for other trees as well. its probably a problem with the BYG biomes creating the large trees. Also maybe add fast leaf decay because the floating leaves are kind of annoying. Other than that thanks for all your hard work. I'm really enjoying the pack!

**Comment by agileMuffin** [comment]
Hi, I am thinking of replacing byg, but until I do I need to see where in other parts it is integrated or whether the player's world would be corrupted/ruined. I would definitely add the fast leaf decay, but I would recommend using botany pots for growing trees so that it doesn't break stuff.

**Comment by Applemyp** [comment]
> Hi, I am thinking of replacing byg, but until I do I need to see where in other parts it is integrated or whether the player's world would be corrupted/ruined. I would definitely add the fast leaf decay, but I would recommend using botany pots for growing trees so that it doesn't break stuff.

Ok thanks, I will use botany pots for now
